import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonHeader, IonToolbar, IonTitle, IonContent, IonMenu, IonMenuButton, IonButtons, IonButton, IonIcon, IonList, IonMenuToggle, IonItem, IonLabel, IonSplitPane, IonAvatar, IonChip, IonRouterLink, IonSearchbar, IonTabBar, IonTabButton, IonBadge, IonRow, IonGrid, IonCard, IonCardContent, IonCardHeader, IonCol, IonInfiniteScroll, IonInfiniteScrollContent, IonBackButton, IonBackdrop, IonCardSubtitle, IonCardTitle, IonToggle, IonAccordionGroup, IonAccordion, IonListHeader, IonTextarea, IonFab, IonFabButton, IonRange, IonSelect, IonSelectOption, IonTabs, IonFooter, IonImg, IonSegment, IonSegmentButton, IonInput, IonModal, IonNote} from '@ionic/angular/standalone';
import { TruncatePipe } from '../core/pipes/truncate.pipe';
import { ZXingScannerModule } from '@zxing/ngx-scanner';
import { AgePipe } from '../core/pipes/age.pipe';
import { RouterModule } from '@angular/router';
import { IonicModule } from '@ionic/angular'
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MaskitoModule } from '@maskito/angular';



@NgModule({
  declarations: [
    //PetListComponent,
    //PetCardComponent,
    TruncatePipe,
    AgePipe
  ],
  imports: [
    IonRouterLink,
    IonChip,
    IonAvatar,
    IonSplitPane,
    IonLabel,
    IonItem,
    IonList,
    IonButton, 
    IonHeader,
    IonToolbar,
    IonTitle,
    IonContent,
    IonMenu,
    IonMenuButton,
    IonButtons,
    IonIcon,
    IonMenuToggle,
    IonList,
    IonSearchbar,
    IonTabBar,
    IonTabButton,
    IonBadge,
    IonRow,
    IonGrid,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCol,
    IonInfiniteScroll,
    IonBackButton,
    IonBackdrop,
    IonCardSubtitle,
    IonCardTitle,
    IonToggle,
    IonAccordionGroup,
    IonAccordion,
    IonListHeader,
    IonTextarea,
    IonFab, IonFabButton, IonRange, IonSelect, IonSelectOption,
    IonInfiniteScrollContent,
    IonTabs,
    IonSegment,
    IonInput,
    IonModal,
    IonSegmentButton,
    FormsModule,
    ZXingScannerModule,
    ReactiveFormsModule,
    ReactiveFormsModule,
    IonicModule,
    
    // ExploreContainerComponent,
    // PetListComponent,
    // PetCardComponent,
  ],
  exports: [
    IonRouterLink,
    IonChip,
    IonAvatar,
    IonSplitPane,
    IonLabel,
    IonItem,
    IonList,
    IonButton, 
    IonHeader,
    IonToolbar,
    IonTitle,
    IonContent,
    IonMenu,
    IonMenuButton,
    IonButtons,
    IonIcon,
    IonMenuToggle,
    IonList,
    IonSearchbar,
    IonTabBar,
    IonTabButton,
    IonBadge,
    IonRow,
    IonGrid,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCol,
    IonInfiniteScroll,
    IonBackButton,
    IonBackdrop,
    IonCardSubtitle,
    IonCardTitle,
    IonToggle,
    IonAccordionGroup,
    IonAccordion,
    IonListHeader,
    IonInfiniteScrollContent,
    IonTextarea,
    IonFab,
    IonFabButton,
    IonRange,
    IonSelect,
    IonSelectOption,
    IonTabs,
    IonSegment,
    IonInput,
    IonModal,
    IonSegmentButton,
    FormsModule,
    ReactiveFormsModule,
    CommonModule,
    // IonicModule,
    // ExploreContainerComponent,
    // PetListComponent,
    // PetCardComponent,
    TruncatePipe,
    AgePipe,
    ZXingScannerModule,
    RouterModule,
    ReactiveFormsModule,
  ]
})
export class SharedModule { }
